#server conf.
server:
  port: 4040
  servlet:
    contextPath: /api/v1

#datasource conf.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authorization
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update